/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.Registro;

/**
 *
 * @author javier
 */
public class Menu extends javax.swing.JFrame {
Registro doc;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        doc=new Registro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuIngresar = new javax.swing.JMenu();
        menuEliminar = new javax.swing.JMenu();
        MenuListar = new javax.swing.JMenu();
        Prestar = new javax.swing.JMenu();
        MenuRegistro = new javax.swing.JMenu();
        MenuVer = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        RegistrarDevol = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jMenuBar1ComponentHidden(evt);
            }
        });

        jMenu1.setText("File");

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuIngresar.setText("Ingresar");
        menuIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIngresarMouseClicked(evt);
            }
        });
        jMenu2.add(menuIngresar);

        menuEliminar.setText("Eliminar");
        menuEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEliminarMouseClicked(evt);
            }
        });
        jMenu2.add(menuEliminar);

        MenuListar.setText("Listar");
        MenuListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuListarMouseClicked(evt);
            }
        });
        jMenu2.add(MenuListar);

        jMenuBar1.add(jMenu2);

        Prestar.setText("Prestar");
        Prestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrestarMouseClicked(evt);
            }
        });

        MenuRegistro.setText("Registro");
        MenuRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuRegistroMouseClicked(evt);
            }
        });
        Prestar.add(MenuRegistro);

        MenuVer.setText("Ver Prestamos");
        MenuVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuVerMouseClicked(evt);
            }
        });
        Prestar.add(MenuVer);

        jMenuBar1.add(Prestar);

        jMenu3.setText("Devolucion");

        RegistrarDevol.setText("Registrar Devolucion");
        RegistrarDevol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarDevolMouseClicked(evt);
            }
        });
        jMenu3.add(RegistrarDevol);

        jMenu4.setText("Ver Registro");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
      System.exit(0);
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIngresarMouseClicked
       Ingresar in=new Ingresar();
       in.setVisible(true);
    }//GEN-LAST:event_menuIngresarMouseClicked

    private void menuEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEliminarMouseClicked
        Eliminar el=new Eliminar();
        el.setVisible(true);
    }//GEN-LAST:event_menuEliminarMouseClicked

    private void MenuListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuListarMouseClicked
        Listar li=new Listar();
        li.setVisible(true);
    }//GEN-LAST:event_MenuListarMouseClicked

    private void jMenuBar1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1ComponentHidden

    private void PrestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrestarMouseClicked
       
    }//GEN-LAST:event_PrestarMouseClicked

    private void MenuRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuRegistroMouseClicked
    Prestamos P =new Prestamos();
        P.setVisible(true);
    }//GEN-LAST:event_MenuRegistroMouseClicked

    private void MenuVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVerMouseClicked
        VerRegistro V =new VerRegistro();
        V.setVisible(true);
    }//GEN-LAST:event_MenuVerMouseClicked

    private void RegistrarDevolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarDevolMouseClicked
        Devolucion D =new Devolucion();
        D.setVisible(true);
    }//GEN-LAST:event_RegistrarDevolMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuListar;
    private javax.swing.JMenu MenuRegistro;
    private javax.swing.JMenu MenuVer;
    private javax.swing.JMenu Prestar;
    private javax.swing.JMenu RegistrarDevol;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuEliminar;
    private javax.swing.JMenu menuIngresar;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
